# Generated by Django 2.2.4 on 2019-08-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('imageURL', models.TextField()),
            ],
        ),
    ]
